version: '3.5'

services:

  vf2:
    privileged: true
    build:
        context: .
        dockerfile: Dockerfile
        # build host dir with docker dir
    volumes:
        - './image:/outport'
    # vf2 kernel passed here
    environment:
        - KERNEL_VERSION=${KERNEL_VERSION}
